Drop TABLE zipcodes;

CREATE TABLE zipcodes
(RecordNumber int, Country string, City string, Zipcode int)
PARTITIONED BY (state string)
CLUSTERED BY (Zipcode) INTO 5 BUCKETS
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',';

--LOAD data into the table
LOAD DATA LOCAL INPATH '/root/zipcodes.csv' INTO TABLE zipcodes;

--Export the result
INSERT OVERWRITE LOCAL DIRECTORY '/root/hiveOutput'
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
SELECT * FROM zipcodes WHERE state='PR' and zipcode=704;
